package com.spring.ai.firstproject.first_project.executor;

import org.springframework.stereotype.Service;

import com.spring.ai.firstproject.first_project.planner.MigrationPlan;
import com.spring.ai.firstproject.first_project.tools.BranchTools;
import com.spring.ai.firstproject.first_project.tools.FileTools;
import com.spring.ai.firstproject.first_project.tools.RepoTools;

@Service
public class MigrationExecutor {

    private final RepoTools repoTools;
    private final FileTools fileTools;
    private final BranchTools branchTools;

    public MigrationExecutor(
            RepoTools repoTools,
            FileTools fileTools,
            BranchTools branchTools) {

        this.repoTools = repoTools;
        this.fileTools = fileTools;
        this.branchTools = branchTools;
    }

    public String execute(MigrationPlan plan) {

        StringBuilder result = new StringBuilder();

        for (MigrationPlan.RepositoryPlan repository
                : plan.repositories()) {

            result.append("\n====================================\n");
            result.append("Repository: ")
                    .append(repository.name())
                    .append("\n");
            result.append("====================================\n");

            // 1. Create repository
            result.append(
                    repoTools.createRepository(
                            repository.name()))
                    .append("\n");

            // 2. Create files and commits on main
            createMainHistory(repository, result);

            // 3. Create branches
            createBranches(repository, result);

            result.append("Completed repository: ")
                    .append(repository.name())
                    .append("\n");
        }

        return result.toString();
    }

    private void createMainHistory(
            MigrationPlan.RepositoryPlan repository,
            StringBuilder result) {

        if (repository.fileTypes() == null
                || repository.fileTypes().isEmpty()) {

            return;
        }

        String filePath = "history.txt";

        for (int i = 1;
                i <= repository.commitCount();
                i++) {

            String content =
                    "Repository: " + repository.name()
                    + "\n"
                    + "Commit number: " + i
                    + "\n"
                    + "Generated by migration AI agent.";

            String commitMessage =
                    "chore: update history " + i;

            String response = fileTools.createOrUpdateFile(
                    repository.name(),
                    "main",
                    filePath,
                    content,
                    commitMessage);

            result.append(response)
                    .append("\n");
        }
    }

    private void createBranches(
            MigrationPlan.RepositoryPlan repository,
            StringBuilder result) {

        if (repository.branches() == null) {
            return;
        }

        for (String branch : repository.branches()) {

            if ("main".equals(branch)) {
                continue;
            }

            String response = branchTools.createBranch(
                    repository.name(),
                    branch,
                    "main");

            result.append(response)
                    .append("\n");
        }
    }
}